/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vendingmachine;

import vending.*;

public class App {

    private static VendingMachine vm;

    public static void main(String[] args) {
        vm = VendingMachineFactory.createVendingMachine(); 
    }
}
