/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package streamapi;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        List<String> stringList = new ArrayList<String>();

        stringList.add("ONE");
        stringList.add("TWO");
        stringList.add("THREE");

        Stream<String> stream = stringList.stream();

        long count = stream
            .map((value) -> { return value.toLowerCase(); })
            .count();

        System.out.println("count = " + count);
    }
}
