/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junitexample;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public int multiply(int x, int y) {
    // the following is just an example
        if (x > 999) {
            throw new IllegalArgumentException("X should be less than 1000");
        }
        // return x / y;
        return x * y;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
