/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tasdiqhasan.junit.first;

public class App {

    public static void main(String[] args) {

        Math mth = new Math();

        System.out.println("Hasil perkalian 2 x 5 adalah " + mth.multiply(2, 5));
    }
}