/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junitexample;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test(expected = IllegalArgumentException.class)
    public void testExceptionIsThrown() {
        App tester = new App();
        tester.multiply(1000, 5);
    }

    @Test
    public void testMultiply() {
        App tester = new App();
        assertEquals("10 x 5 must be 50", 50, tester.multiply(10, 5));
    }
}
