/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;

public class BicycleTest {
    @Test public void testBicycleCanChangeGear() {
        Bicycle classUnderTest = new Bicycle(2,3,4);
        classUnderTest.setGear(3);
        assertEquals("Bicycle gear is 3", 3, classUnderTest.gear);
    }
}
