/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;

public class MountainBikeTest {
    @Test public void testMountainBikeCanSetHeight() {
        MountainBike classUnderTest = new MountainBike(5,6,7,8);
        classUnderTest.setHeight(24);
        assertEquals("Mountain Bike seat height is 24", 24, classUnderTest.seatHeight);
    }
}
