/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package purefunction;

class ObjectWithPureFunction{

    public int sum(int a, int b) {
        return a + b;
    }
}

public class App {
    
    public static void main(String[] args) {

        ObjectWithPureFunction obj = new ObjectWithPureFunction();

        System.out.println("Penjumlahan dari 5 dan 12 adalah "+ obj.sum(5, 12));
    }
}
