/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mongo;

import com.mongodb.client.MongoDatabase; 
import com.mongodb.MongoClient; 
import com.mongodb.MongoCredential; 

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());

        // Creating a Mongo client 
        MongoClient mongo = new MongoClient( "localhost" , 27017 ); 

        // Creating Credentials 
        // MongoCredential credential; 
        // credential = MongoCredential.createCredential("", "myDb", "password".toCharArray()); 
        System.out.println("Connected to the database successfully");  

        // Accessing the database 
        MongoDatabase database = mongo.getDatabase("test"); 
        // System.out.println("Credentials ::"+ credential); 
    }
}
