/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package classesexample;

import pitKu.*;

public class App {

    public static void main(String[] args) {

        Bicycle pitJengki = new Bicycle(10,20,30);
        MountainBike pitGunung = new MountainBike(5, 8,16,24);


        System.out.println("Pit jengki le ngebut semene : " + pitJengki.speed);
        System.out.println("Pit gunung le ngoyak kecepatan : " + pitGunung.speed);

    }
}
